FROM node:lts-buster

# Create app directory
WORKDIR /usr/src/app
 
# Copy dependency definitions
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json

# Install dependencies
#RUN npm set progress=false \
#    && npm config set depth 0 \
#    && npm i install
RUN npm ci

COPY ./ /usr/src/app/

# Expose the port the app runs in
EXPOSE 3000
 
# Serve the app
CMD npm dev