# This workflow will build the project then tag the docker image.

name: Redscan Scanner CI.

on:
  push:
    tags:
      - '*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo "tag=${GITHUB_REF#refs/*/}" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build & Push the image to GitHub Packages
      uses: docker/build-push-action@v4
      with:
        context: .
        file: './Dockerfile.prod'
        tags: ghcr.io/deddobifu/redscan-magellan-front/redscan-magellan-front:${{ steps.vars.outputs.tag }}
        push: true