FROM node:lts-buster

# Create app directory
WORKDIR /usr/src/app
 
# Copy dependency definitions
COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
COPY config-overrides.js ./config-overrides.js

# Install dependencies
#RUN npm set progress=false \
#    && npm config set depth 0 \
#    && npm i install
RUN npm ci

COPY ./ /usr/src/app/

# Expose the port the app runs in
EXPOSE 3000
 
# Serve the app
CMD npm start --host 0.0.0.0 --port 3000 --disableHostCheck true --reset-cache