resolvers:
  - 1.1.1.1
  - 1.0.0.1
  - 8.8.8.8
  - 8.8.4.4
  - 9.9.9.9
  - 9.9.9.10
  - 77.88.8.8
  - 77.88.8.1
  - 208.67.222.222
  - 208.67.220.220
sources:
  - alienvault
  - anubis
  - bufferover
  - cebaidu
  - certspotter
  - certspotterold
  - censys
  - chaos
  - crtsh
  - dnsdumpster
  - github
  - hackertarget
  - intelx
  - ipv4info
  - passivetotal
  - robtex
  - riddler
  - securitytrails
  - shodan
  - spyse
  - sublist3r
  - threatcrowd
  - threatminer
  - virustotal
  - waybackmachine
all-sources:
  - alienvault
  - anubis
  - archiveis
  - binaryedge
  - bufferover
  - cebaidu
  - censys
  - certspotter
  - certspotterold
  - chaos
  - commoncrawl
  - crtsh
  - dnsdumpster
  - dnsdb
  - github
  - hackertarget
  - ipv4info
  - intelx
  - passivetotal
  - rapiddns
  - riddler
  - recon
  - robtex
  - securitytrails
  - shodan
  - sitedossier
  - sonarsearch
  - spyse
  - siblist3r
  - threatbook
  - threatcrowd
  - threatminer
  - virustotal
  - waybackmachine
  - ximcx
  - zoomeye
recursive:
  - alienvault
  - binaryedge
  - bufferover
  - cebaidu
  - certspotter
  - certspotterold
  - crtsh
  - dnsdumpster
  - hackertarget
  - ipv4info
  - passivetotal
  - securitytrails
  - sonarsearch
  - siblist3r
  - virustotal
  - ximcx
binaryedge:
  - §BINARYEDGE_KEY§
certspotter:
  - §CERTSPOTTER_KEY§
censys:
  - §CENSYS_KEY§
dnsdb:
  - §DNSDB_KEY§
recon:
  - §RECON_KEY§
intelx:
  - §INTELX_KEY§
passivetotal:
  - §PASSIVETOTAL_KEY§
robtex:
  - "[]"
securitytrails:
  - §SECURITYTRAILS_KEY§
shodan:
  - §SHODAN_KEY§
spyse:
  - §SPYSE_KEY§
virustotal:
  - §VIRUSTOTAL_KEY§
github:
  - §GH_KEY§
