#
# Docker compose file for REDSCAN-MAGELLAN-BACK.
#
version: "3.8"
services:

  redscan-saas-explorer:
    image: deddobifu/redscan-saas-explorer:1.0.0
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - DATALAKE_ELASTIC_URL=http://elasticsearch:9200
      - DATALAKE_ELASTIC_USERNAME=
      - DATALAKE_ELASTIC_PASSWORD=
      - CACHE_MANAGER_URL=http://redscan-cache:8080
    volumes:
      - ./logs:/logs
      - ./resources/redscan-saas-explorer:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-vulnerability:
    image: deddobifu/redscan-vulnerability:1.0.0
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_RABBITMQ_PORT=5672
      - DATALAKE_ELASTIC_URL=http://elasticsearch:9200
      - DATALAKE_ELASTIC_USERNAME=
      - DATALAKE_ELASTIC_PASSWORD=
      - CACHE_MANAGER_URL=http://redscan-cache:8080
      - MANTIS_API_URL=http://mantisbt:80/api/soap/mantisconnect.php
      - MANTIS_API_USERNAME=administrator
      - MANTIS_API_PASSWORD=redscan
    volumes:
      - ./logs:/logs
      - ./resources/redscan-vulnerability:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.14.1
    ports:
      # - "exposé:inner"
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
      - indices.id_field_data.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
        test: curl -s http://localhost:9200/_cluster/health -k | grep -vq '"status":"red"'
        interval: 20s
        retries: 10

  rabbitmq:
    image: rabbitmq:3.12.13-management
    ports:
      # - "exposé:inner"
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "/rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3

  keycloak:
    image: quay.io/keycloak/keycloak:21.1.1
    ports:
      # - "exposé:inner"
      - "8080:8080"
    env_file:
      - resources/keycloak/keycloak.env
    volumes:
      - ./resources/keycloak/conf:/opt/keycloak/data/import/
    command:
      - start-dev 
      - --import-realm
      - --hostname-path=/auth
      - --proxy edge
      - --hostname-url https://localhost/auth/
      - --hostname-admin-url https://localhost/auth/

  mantisbt:
    image: deddobifu/redscan-mantisbt:1.0.2
    ports:
      - "8890:80"
    env_file:
      - resources/mantis/mantisbt.env
    depends_on:
      - mantisbtdb
    restart: always

  mantisbtdb:
    image: mariadb:11.3.2
    env_file:
      - resources/mantis/mantisbtdb.env
    volumes:
      - ./resources/mantis/scripts/bugtracker.sql:/docker-entrypoint-initdb.d/1.sql
    # Set default collation so Mantis does not complain about latin1
    command: ['mariadbd', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']

  redscan-cache:
    image: deddobifu/redscan-cache:1.0.0
    volumes:
      - ./logs:/logs
      - ./resources/redscan-cache:/conf
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-rproxy:
    image: deddobifu/redscan-rproxy:1.0.0
    volumes:
      - ./resources/rproxy/apache.conf:/usr/local/apache2/conf/redscan.conf
      - ./resources/rproxy/certs/:/usr/local/apache2/conf/certs/
      - ./resources/rproxy/logs:/usr/local/apache2/logs/
    ports:
      - 443:443
    extra_hosts:
      - localhost:127.0.0.1
