#
# Docker compose file for plugin development.
#
version: "3.8"
services:

  redscan-vulnerability:
    image: deddobifu/redscan-vulnerability:1.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  redscan-cache:
    image: deddobifu/redscan-cache:1.0.0
    depends_on:
      rabbitmq:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy

  elasticsearch:
    image: elasticsearch:8.12.2
    ports:
      # - "exposé:inner"
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms4096m -Xmx4096m"
      - xpack.security.enabled=false
      - indices.id_field_data.enabled=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
        test: curl -s http://localhost:9200/_cluster/health -k | grep -vq '"status":"red"'
        interval: 20s
        retries: 10

  rabbitmq:
    image: rabbitmq:3.12.13-management
    ports:
      # - "exposé:inner"
      - "15671:15671"
      - "5672:5672"
    environment:
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbitmq_management path_prefix "/rabbitmq"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 3