  
# This workflow will build the java project then build the docker image.

name: Redscan Scanner CI.

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Build & Push the image to GitHub Packages
      uses: docker/build-push-action@v1
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_TOKEN }}
        registry: ghcr.io
        repository: deddobifu/redscan-mantisbt/redscan-mantisbt
        tags: latest
        
