---

- import_playbook: services/apache.yaml
- import_playbook: services/keycloak.yaml
- import_playbook: services/elastic.yaml
- import_playbook: services/kibana.yaml
- import_playbook: services/rabbitmq.yaml
- import_playbook: services/mantisbt.yaml
- import_playbook: services/services.yaml
- import_playbook: services/magellan.yaml