apiVersion: v1
kind: Deployment
metadata:
  name: "{{plugin}}"
spec: 
  selector:
    matchLabels:
      app: "{{plugin}}"
  replicas: {{plugins[plugin].replicas | int}}
  template:
    metadata:
      labels:
        app: "{{plugin}}"
    spec: 
      containers: 
      - image: {{plugins[plugin].image}}:{{plugins[plugin].version}}
        name: "{{plugin}}"
        envFrom:
          - configMapRef: 
              name: "general-configmap"
        env:
          - name: MANTIS_API_URL
            value: "http://{{hostvars[groups['_service_mantisbt'][0]]['private_ipv4_addresses'][0]}}/api/soap/mantisconnect.php"
          - name: MANTIS_API_USERNAME
            value: "{{mantisbt_admin_username}}"
          - name: MANTIS_API_PASSWORD
            value: "{{mantisbt_admin_password}}"
        volumeMounts:
          - name: log4j-config-volume
            mountPath: /conf
      volumes:
        - name: log4j-config-volume
          configMap:
            name: "{{plugin}}-log4j-configmap"
            items:
            - key: log4j2.xml
              path: log4j2.xml

