name: Deploy java docker image

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory to deploy'
        default: plugins
      project:
        description: 'Project to build'
        required: true
      version:
        description: 'Docker image version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: ${{ github.event.inputs.project }}

    steps:

    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Convert inputs to lowercase
      run: echo "PROJECT=$(echo $PROJECT | awk '{print tolower($0)}')" >> $GITHUB_ENV

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Ensure Checkstyle
      run: mvn -B checkstyle:check --file ${{ github.event.inputs.dir }}/${{ github.event.inputs.project }}/pom.xml

    - name: Build with Maven
      run: mvn -B install --file ${{ github.event.inputs.dir }}/${{ github.event.inputs.project }}/pom.xml

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.event.inputs.dir }}/${{ github.event.inputs.project }}/
        push: true
        tags: deddobifu/${{ env.PROJECT }}:${{ github.event.inputs.version }}
        platforms: linux/amd64,linux/arm64
