name: Deploy java docker image

on:
  workflow_dispatch:
    inputs:
      dir:
        description: 'Directory to deploy'
        default: utils
      project:
        description: 'Project to build'
        default: Redscan-Base
      version:
        description: 'Docker image version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT: ${{ github.event.inputs.project }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ${{ github.event.inputs.dir }}/${{ github.event.inputs.project }}/
        push: true
        tags: deddobifu/${{ env.PROJECT }}:${{ github.event.inputs.version }}
        platforms: linux/amd64,linux/arm64
